//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string maKH { get; set; }
        public string hoTenKH { get; set; }
        public string emailKH { get; set; }
        public string sdtKH { get; set; }
        public string diaChiKH { get; set; }
        public string matKhau { get; set; }
    }
}
