//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThueXeEntities : DbContext
    {
        public ThueXeEntities()
            : base("name=ThueXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<mail> mails { get; set; }
        public virtual DbSet<rent> rents { get; set; }
        public virtual DbSet<rentDetail> rentDetails { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
